blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path("posts/", views.PostListView.as_view(), name="post_list"),
    path("posts/load-more/", views.LoadMorePostsView.as_view(), name="load_more_posts"),
    path("posts/search/", views.PostSearchView.as_view(), name="post_search"),
    path('posts/add/', views.CreatePostView.as_view(), name="new_post"),
    path('posts/<int:post_id>/edit/', views.PostUpdateView.as_view(), name="edit_post"),
    path('posts/<int:post_id>/delete/', views.PostDeleteView.as_view(), name="remove_post"),
    path('posts/<slug:post_slug>/', views.PostDetailView.as_view(), name="post_detail"),
    path('posts/category/<slug:category_slug>/', views.CategoryPostsView.as_view(), name="category_posts"),
    path('posts/tag/<slug:tag_slug>/', views.TagPostsView.as_view(), name="tag_posts"),
    path('posts/<int:post_id>/like/', views.PostLikeToggleView.as_view(), name="post_like"),
    path('posts/<int:post_id>/dislike/', views.PostDislikeToggleView.as_view(), name="post_dislike"),
    path('posts/<int:post_id>/toggle-favorite/', views.PostFavoriteToggleView.as_view(), name="post_favorite_toggle"),
    path("posts/<int:post_id>/comments/add/", views.AddCommentView.as_view(), name="add_comment"),
    path('posts/<int:post_id>/comments/load-more/', views.LoadMoreCommentsView.as_view(), name="load_more_comments"),
    path('news/important/toggle-subscription/', views.ToggleImportantNewsSubscriptionView.as_view(), name='toggle_important_news_subscription'),
    path('', views.MainPageView.as_view(), name='main_page'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('profile/', include("users.urls")),
    path('', include("blog.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
# from django.contrib.auth.views import PasswordChangeView
from . import views

app_name = 'users'

urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
    path('activate-account/<uidb64>/<token>/', views.ActivateAccountView.as_view(), name='activate_account'),
    path('login/', views.CustomLoginView.as_view(), name="login"),
    path('logout/', views.CustomLogoutView.as_view(), name='logout'),

    path('phone-number/set/', views.set_phone_number, name='set_phone_number'),
    path('phone-number/mark-verified/', views.mark_phone_number_as_verified, name='mark_phone_number_as_verified'),

    path('password-change/', views.CustomPasswordChangeView.as_view(), name='password_change'),
    # path('password-change/', PasswordChangeView.as_view(
    #     template_name='users/pages/password_change.html',
    #     success_url=reverse_lazy('users:password_change_done')
    # ), name='password_change'),
    path('password-change/done/', views.PasswordChangeDoneView.as_view(), name='password_change_done'),


    path('password-reset/', auth_views.PasswordResetView.as_view(
        template_name="users/pages/password_reset.html",
        email_template_name='users/emails/password_reset.txt',
        html_email_template_name='users/emails/password_reset.html',
        subject_template_name='users/emails/subjects/password_reset.txt',
        success_url=reverse_lazy("users:password_reset_instructions_sent")
    ), name='password_reset'),

    path('password-reset/instructions-sent/', auth_views.PasswordResetDoneView.as_view(
        template_name="users/pages/password_reset_instructions_sent.html"
    ), name='password_reset_instructions_sent'),

    path('password-reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name="users/pages/password_reset_form.html",
        success_url=reverse_lazy('users:password_reset_complete')
    ), name='password_reset_set_new'),

    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name="users/pages/password_reset_complete.html"
    ), name='password_reset_complete'),


    path('my/password-reset/', views.ProfilePasswordResetView.as_view(), name="profile_password_reset"),

    path('my/password-reset/instructions-sent/', auth_views.PasswordResetDoneView.as_view(
        template_name="users/pages/password_reset_profile_instructions_sent.html"
    ), name='profile_password_reset_instructions_sent'),


    path("toggle-theme/", views.toggle_theme, name="toggle_theme"),

    path("favorite-posts/", views.FavoritePostsView.as_view(), name="favorite_posts"),
    path('settings/', views.SettingsView.as_view(), name='settings'),
    path("<str:user_username>/", views.ProfileView.as_view(), name='profile'),
]

templates/layouts/base.html
{% load static %}
{% load django_bootstrap5 %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Блог{% endblock title %}</title>
    <link rel="icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon">
    
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css">

    <link rel="stylesheet" href="{% static 'css/core.css' %}">
    {% block styles %}{% endblock styles %}

    <script src="{% static 'js/core.js' %}" type="module" defer></script>
    {% block scripts %}{% endblock scripts %}
</head>
<body class="d-flex flex-column min-vh-100" data-bs-theme="{{ current_theme }}" data-theme-toggle-url="{% url "users:toggle_theme" %}">
    <header class="rounded-bottom border-bottom border-2 header">
        <nav class="navbar navbar-expand-sm">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'blog:main_page' %}">Pikabu</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                    aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link {% if request.resolver_match.url_name == 'post_list' %}active{% endif %}" aria-current="page" href="{% url 'blog:post_list' %}">Список постов</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% if request.resolver_match.url_name == 'new_post' %}active{% endif %}" href="{% url 'blog:new_post' %}">Создать пост</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% if request.resolver_match.url_name == 'post_search' %}active{% endif %}" href="{% url 'blog:post_search' %}">Поиск постов</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <div class="h-100 d-flex flex-column justify-content-center">
                                <button id="themeToggleBtn" class="btn btn-outline-primary border-0">
                                    <i class="bi bi-{% if current_theme == 'dark' %}moon{% else %}sun{% endif %}-fill"></i>
                                </button>
                            </div>
                        </li>
                        {% if request.user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link {% if request.resolver_match.url_name == 'profile' and request.resolver_match.kwargs.user_username == request.user.username %}active{% endif %}" href="{% url "users:profile" request.user.username %}"><i class="bi bi-person-circle me-1"></i>{{ request.user }}</a>
                            </li>
                            <li class="nav-item">
                                <div class="h-100 d-flex flex-column justify-content-center">
                                    <form method="POST" action="{% url 'users:logout' %}">
                                        {% csrf_token %}
                                        <button type="submit" class="btn text-danger border-0">
                                            <i class="bi bi-box-arrow-right"></i> Выйти
                                        </button>
                                    </form>
                                </div>
                            </li>
                        {% else %}
                            <li class="nav-item">
                                <a class="nav-link {% if request.resolver_match.url_name == 'login' %}active{% endif %}" href="{% url 'users:login' %}">Войти</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link {% if request.resolver_match.url_name == 'register' %}active{% endif %}" href="{% url 'users:register' %}">Регистрация</a>
                            </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <main class="flex-grow-1">{% block content %}{% endblock content %}</main>
    <footer class="rounded-top border-top border-2 py-3 footer">
        <div class="container-fluid">
            <div class="text-center">
                &copy; Все права защищены 2025
            </div>
        </div>
    </footer>

    {% comment %} <button id="scrollToTopBtn" class="scroll-to-top"><i class="bi bi-arrow-up"></i></button> {% endcomment %}

    {% if messages %}
        <div class="position-fixed bottom-0 end-0 p-3">
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }} alert-dismissible fade show m-0 auto-dismiss" role="alert">
                    {{ message }}
                    <button class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endfor %}
        </div>
    {% endif %}
</body>
</html>