blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path("posts/", views.PostListView.as_view(), name="post_list"),
    path("posts/load-more/", views.LoadMorePostsView.as_view(), name="load_more_posts"),
    path("posts/search/", views.PostSearchView.as_view(), name="post_search"),
    path('posts/add/', views.CreatePostView.as_view(), name="new_post"),
    path('posts/<int:post_id>/edit/', views.PostUpdateView.as_view(), name="edit_post"),
    path('posts/<int:post_id>/delete/', views.PostDeleteView.as_view(), name="remove_post"),
    path('posts/<slug:post_slug>/', views.PostDetailView.as_view(), name="post_detail"),
    path('posts/category/<slug:category_slug>/', views.CategoryPostsView.as_view(), name="category_posts"),
    path('posts/tag/<slug:tag_slug>/', views.TagPostsView.as_view(), name="tag_posts"),
    path('posts/<int:post_id>/like/', views.PostLikeToggleView.as_view(), name="post_like"),
    path('posts/<int:post_id>/dislike/', views.PostDislikeToggleView.as_view(), name="post_dislike"),
    path('posts/<int:post_id>/toggle-favorite/', views.PostFavoriteToggleView.as_view(), name="post_favorite_toggle"),
    path("posts/<int:post_id>/comments/add/", views.AddCommentView.as_view(), name="add_comment"),
    path('posts/<int:post_id>/comments/load-more/', views.LoadMoreCommentsView.as_view(), name="load_more_comments"),
    path('news/important/toggle-subscription/', views.ToggleImportantNewsSubscriptionView.as_view(), name='toggle_important_news_subscription'),
    path('', views.MainPageView.as_view(), name='main_page'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('profile/', include("users.urls")),
    path('', include("blog.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
# from django.contrib.auth.views import PasswordChangeView
from . import views

app_name = 'users'

urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
    path('activate-account/<uidb64>/<token>/', views.ActivateAccountView.as_view(), name='activate_account'),
    path('login/', views.CustomLoginView.as_view(), name="login"),
    path('logout/', views.CustomLogoutView.as_view(), name='logout'),

    path('phone-number/set/', views.set_phone_number, name='set_phone_number'),
    path('phone-number/mark-verified/', views.mark_phone_number_as_verified, name='mark_phone_number_as_verified'),

    path('password-change/', views.CustomPasswordChangeView.as_view(), name='password_change'),
    # path('password-change/', PasswordChangeView.as_view(
    #     template_name='users/pages/password_change.html',
    #     success_url=reverse_lazy('users:password_change_done')
    # ), name='password_change'),
    path('password-change/done/', views.PasswordChangeDoneView.as_view(), name='password_change_done'),


    path('password-reset/', auth_views.PasswordResetView.as_view(
        template_name="users/pages/password_reset.html",
        email_template_name='users/emails/password_reset.txt',
        html_email_template_name='users/emails/password_reset.html',
        subject_template_name='users/emails/subjects/password_reset.txt',
        success_url=reverse_lazy("users:password_reset_instructions_sent")
    ), name='password_reset'),

    path('password-reset/instructions-sent/', auth_views.PasswordResetDoneView.as_view(
        template_name="users/pages/password_reset_instructions_sent.html"
    ), name='password_reset_instructions_sent'),

    path('password-reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name="users/pages/password_reset_form.html",
        success_url=reverse_lazy('users:password_reset_complete')
    ), name='password_reset_set_new'),

    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name="users/pages/password_reset_complete.html"
    ), name='password_reset_complete'),


    path('my/password-reset/', views.ProfilePasswordResetView.as_view(), name="profile_password_reset"),

    path('my/password-reset/instructions-sent/', auth_views.PasswordResetDoneView.as_view(
        template_name="users/pages/password_reset_profile_instructions_sent.html"
    ), name='profile_password_reset_instructions_sent'),


    path("toggle-theme/", views.toggle_theme, name="toggle_theme"),

    path("favorite-posts/", views.FavoritePostsView.as_view(), name="favorite_posts"),
    path('settings/', views.SettingsView.as_view(), name='settings'),
    path("<str:user_username>/", views.ProfileView.as_view(), name='profile'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from phonenumber_field.modelfields import PhoneNumberField


class CustomUser(AbstractUser):
  THEME_CHOICES = [
    ("light", "Светлая"),
    ("dark", "Тёмная")
  ]

  email = models.EmailField(unique=True, null=True, blank=True)

  phone_number = PhoneNumberField(null=True, blank=True, verbose_name='Номер телефона')
  phone_number_verified = models.BooleanField(default=False, verbose_name='Номер телефона подтверждён')
  
  avatar = models.ImageField(upload_to="user_avatars/", null=True, blank=True)
  selected_theme = models.CharField(choices=THEME_CHOICES, default="dark")
  subscribed_to_important_news = models.BooleanField(
    default=False,
    verbose_name="Подписан на важные новости"
  )

  class Meta:
    verbose_name = 'Пользователь'
    verbose_name_plural = "Пользователи"

users/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth import get_user_model

User = get_user_model()


class CustomAuthenticationForm(AuthenticationForm):
  def __init__(self, request = ..., *args, **kwargs):
    super().__init__(request, *args, **kwargs)

    self.fields['username'].label = 'Email или имя пользователя'
    self.fields['username'].widget.attrs.update({
      'placeholder': 'Введите email или имя пользователя'
    })
    self.error_messages.update({
      'invalid_login': (
        "Пожалуйста, введите корректные email/имя пользователя и пароль. "
        "Обратите внимание, что оба поля могут быть чувствительны к регистру."
      ),
      'inactive': "Аккаунт не активирован. Проверьте почту для активации."
    })


class CustomUserCreationForm(UserCreationForm):
  class Meta:
    model = User
    fields = ("username", "email", "password1", "password2")

users/views.py
from django.contrib.auth import get_user_model
from django.views.generic import CreateView, DetailView, ListView, TemplateView, View
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView, PasswordResetView
from django.views.generic.list import MultipleObjectMixin
from django.urls import reverse_lazy
from django.contrib import messages
from django.http import JsonResponse
from django.views.decorators.http import require_POST
from django.shortcuts import redirect
from django.contrib.auth.tokens import default_token_generator
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_str
from django.core.mail import send_mail
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from phonenumber_field.phonenumber import PhoneNumber
from django.contrib.auth.decorators import login_required
# from django.conf import settings

from config.settings import LOGIN_REDIRECT_URL, DEFAULT_FROM_EMAIL, FIREBASE_API_KEY
from blog.models import Post
from .forms import CustomAuthenticationForm, CustomUserCreationForm

User = get_user_model()


class RegisterView(CreateView):
    template_name = 'users/pages/register.html'
    form_class = CustomUserCreationForm

    def form_valid(self, form):
        # Сохраняем пользователя как неактивного
        user = form.save(commit=False)
        user.is_active = False
        user.save()

        # Отправляем письмо активации
        self.send_activation_email(user)

        messages.success(
            self.request, 
            'Регистрация прошла успешно! Проверьте почту для активации аккаунта.'
        )
        return redirect('users:login')
        # Используем явный redirect, чтобы избежать повторного form.save() в super().form_valid(form)
        # второй save() менял пользователя и делал токен недействительным

    def send_activation_email(self, user):
        token = default_token_generator.make_token(user)
        uidb64 = urlsafe_base64_encode(force_bytes(user.id))
        
        activation_url = self.request.build_absolute_uri(
            reverse_lazy('users:activate_account', kwargs={'uidb64': uidb64, 'token': token})
        )
        
        site_name = get_current_site(self.request).name

        subject = render_to_string('users/emails/subjects/activate_account.txt', {
            'site_name': site_name,
        })
        message = render_to_string('users/emails/activate_account.txt', {
            'site_name': site_name,
            'activation_url': activation_url
        })
        html_message = render_to_string('users/emails/activate_account.html', {
            'site_name': site_name,
            'activation_url': activation_url
        })

        send_mail(
            subject=subject,
            message=message,  # Текстовая версия
            html_message=html_message,  # HTML версия
            from_email=DEFAULT_FROM_EMAIL,
            recipient_list=[user.email]
        )


class ActivateAccountView(View):
    def get(self, request, uidb64, token):
        try:
            uid = force_str(urlsafe_base64_decode(uidb64))
            user = User.objects.get(pk=uid)
        except (TypeError, ValueError, User.DoesNotExist):
            user = None

        if user and default_token_generator.check_token(user, token):
            user.is_active = True
            user.save()
            messages.success(request, 'Аккаунт успешно активирован! Теперь вы можете войти.')
            return redirect('users:login')
        else:
            messages.error(request, 'Ссылка активации недействительна или устарела.')
            return redirect('users:register')


class CustomLoginView(LoginView):
    template_name = 'users/pages/login.html'
    authentication_form = CustomAuthenticationForm

    def get_success_url(self):
        next_url = self.request.GET.get('next', LOGIN_REDIRECT_URL)
        if next_url == LOGIN_REDIRECT_URL:
            return reverse_lazy(next_url, kwargs={'user_username': self.request.user.username})
        return next_url
    
    def form_invalid(self, form):
        messages.warning(self.request, 'Ошибка входа!')

        return super().form_invalid(form)


class CustomLogoutView(LogoutView):
    next_page = reverse_lazy('blog:post_list')


@require_POST
@login_required
def set_phone_number(request):
    try:
        # Преобразуем строку в объект PhoneNumber
        parsed_phone_number = PhoneNumber.from_string(request.POST.get('phone_number'), region='RU')
        if parsed_phone_number.is_valid():
            # Проверяем, не пытается ли пользователь установить тот же номер телефона
            if request.user.phone_number == parsed_phone_number:
                messages.info(request, 'Этот номер телефона уже привязан к вашему аккаунту')
                return redirect('users:settings')
            
            # Проверяем, не подтвержден ли этот номер телефона у другого пользователя
            user_verified_this_number = User.objects.filter(
                phone_number=parsed_phone_number, 
                phone_number_verified=True
            )
            
            if user_verified_this_number.exists():
                messages.warning(request, 'Этот номер телефона уже используется другим пользователем')
                return redirect('users:settings')

            # Определяем сообщение в зависимости от того, был ли номер телефона до этого
            if request.user.phone_number:
                message = 'Номер телефона успешно изменён'
            else:
                message = 'Номер телефона успешно добавлен'

            request.user.phone_number = parsed_phone_number
            request.user.phone_number_verified = False  # Сбрасываем статус верификации
            request.user.save()
            messages.success(request, message)
        else:
            messages.warning(request, 'Некорректный формат номера телефона')
    except Exception as e:
        messages.warning(request, 'Указанное вами, похоже, не является номером телефона.')
    
    return redirect('users:settings')


@require_POST
@login_required
def mark_phone_number_as_verified(request):
    # Клиент уже проверил код
    # Обновляем статус верификации номера телефона
    request.user.phone_number_verified = True
    request.user.save()

    # Удаляем этот номер телефона у других пользователей
    users_not_verified_this_number = User.objects.filter(
        phone_number=request.user.phone_number
    ).exclude(id=request.user.id)

    if users_not_verified_this_number.exists():
        for user in users_not_verified_this_number:
            user.phone_number = None
            user.save()
    
    return JsonResponse({'success': True})


class CustomPasswordChangeView(PasswordChangeView):
    template_name = 'users/pages/password_change.html'
    success_url = reverse_lazy('users:password_change_done')
    
    def form_valid(self, form):
        messages.success(self.request, 'Пароль успешно изменен!')
        return super().form_valid(form)


class PasswordChangeDoneView(TemplateView):
    template_name = 'users/pages/password_change_done.html'


class ProfilePasswordResetView(PasswordResetView):
    template_name="users/pages/password_reset_profile.html"
    email_template_name='users/emails/password_reset.txt',
    html_email_template_name='users/emails/password_reset.html',
    subject_template_name='users/emails/subjects/password_reset.txt'
    success_url=reverse_lazy("users:profile_password_reset_instructions_sent")

    def post(self, request, *args, **kwargs):
        request.POST = request.POST.copy()
        request.POST['email'] = request.user.email

        messages.success(request, f'Письмо отправлено на {request.user.email}')

        return super().post(request, *args, **kwargs)


@require_POST
def toggle_theme(request):
    if request.user.is_authenticated:
        # Для авторизованных — меняем в базе
        new_theme = 'light' if request.user.selected_theme == 'dark' else 'dark'
        request.user.selected_theme = new_theme
        request.user.save(update_fields=["selected_theme"])
    else:
        # Для неавторизованных — меняем в сессии
        current_theme = request.session.get('theme', 'dark')
        new_theme = 'light' if current_theme == 'dark' else 'dark'
        request.session['theme'] = new_theme
    
    return JsonResponse({'new_theme': new_theme})


class ProfileView(DetailView, MultipleObjectMixin):
    model = User
    template_name = 'users/pages/profile.html'
    slug_field = 'username'
    slug_url_kwarg = 'user_username'
    context_object_name = 'user' # Теперь обязательно
    paginate_by = 5

    def get_context_data(self, **kwargs):
        posts = Post.objects.filter(
            author=self.object
        ).order_by('-created_at')

        # Контекст теперь включает paginator, page_obj, is_paginated
        context = super().get_context_data(object_list=posts, **kwargs)
        
        context['posts'] = context['object_list']
        
        del context['object_list']

        return context


class FavoritePostsView(ListView):
    model = Post
    template_name = 'users/pages/favorite_posts.html'
    context_object_name = "posts"
    paginate_by = 2

    def get_queryset(self):
        return self.request.user.favorite_posts.all()


class SettingsView(TemplateView):
    """Страница настроек профиля"""
    template_name = 'users/pages/settings.html'
    extra_context = {
        'FIREBASE_API_KEY': FIREBASE_API_KEY,
    }

users/templates/users/pages/favorite_posts.html
{% extends "users/layouts/profile_base.html" %}
{% load static %}

{% block title %}Избранные посты{% endblock title %}

{% block styles %}
  {{ block.super }}
  <link rel="stylesheet" href="{% static "blog/css/includes/post_container.css" %}">
{% endblock styles %}

{% block scripts %}
    <script src="{% static "blog/js/favorites.js" %}" type="module" defer></script>
{% endblock scripts %}

{% block profile_content %}
  <h1 class="text-center">Избранные посты</h1>

  <div class="container" data-page-type="favorite-posts">
    {% for post in posts %}
      {% include 'blog/includes/post_container.html' %}
    {% empty %}
      <p class="text-center">Пока нет избранных постов.</p>
    {% endfor %}

    {% include "blog/includes/pagination.html" %}
  </div>
{% endblock profile_content %}

users/templates/users/pages/login.html
{% extends "layouts/base.html" %}
{% load django_bootstrap5 %}

{% block title %}Вход в аккаунт{% endblock title %}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card shadow">
                <div class="card-body">
                    <h1 class="card-title text-center mb-4">Вход в аккаунт</h1>
                    
                    <form method="POST">
                        {% csrf_token %}

                        {% bootstrap_form form %}
                        
                        <div class="d-grid gap-2 mb-3">
                            <button type="submit" class="btn btn-primary">
                                <i class="bi bi-box-arrow-in-right me-2"></i>Войти
                            </button>
                        </div>
                    </form>

                    <div class="text-center">
                        <a href="{% url 'users:password_reset' %}" class="text-decoration-none">
                            <i class="bi bi-key me-1"></i>Забыли пароль?
                        </a>
                    </div>

                    <div class="text-center mt-3">
                        <p class="text-muted">Нет аккаунта?
                            <a href="{% url 'users:register' %}" class="text-decoration-none ms-1">
                                Зарегистрироваться
                            </a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

users/templates/users/pages/password_change.html
{% extends "users/layouts/profile_base.html" %}
{% load django_bootstrap5 %}

{% block title %}Смена пароля{% endblock title %}

{% block profile_content %}
<div class="card">
  <div class="card-header">
    <h2 class="card-title mb-0">
      <i class="bi bi-shield-lock me-2"></i>Смена пароля
    </h2>
  </div>
  <div class="card-body">
    <form method="post">
      {% csrf_token %}

      {% bootstrap_form form %}

      <div class="d-flex gap-2 mt-4">
        <button type="submit" class="btn btn-primary">
          <i class="bi bi-check-lg me-2"></i>Сменить пароль
        </button>
        <a href="javascript:history.back()" class="btn btn-outline-danger">
          <i class="bi bi-arrow-left me-2"></i>Назад
        </a>
      </div>
    </form>
  </div>
</div>
{% endblock profile_content %}

users/templates/users/pages/password_change_done.html
{% extends "users/layouts/profile_base.html" %}

{% block title %}Пароль изменен{% endblock title %}

{% block profile_content %}
<div class="card">
  <div class="card-body text-center py-5">
    <div class="mb-4">
      <i class="bi bi-check-circle-fill text-success fs-1"></i>
    </div>
    <h2 class="card-title mb-3">Пароль успешно изменен!</h2>
    <p class="text-muted mb-4">Ваш пароль был успешно изменен.</p>
    <div class="d-flex justify-content-center gap-2">
      <a href="{% url 'users:profile' user.username %}" class="btn btn-primary">
        <i class="bi bi-person me-2"></i>Вернуться в профиль
      </a>
      <a href="{% url 'blog:main_page' %}" class="btn btn-outline-primary">
        <i class="bi bi-house me-2"></i>На главную
      </a>
    </div>
  </div>
</div>
{% endblock profile_content %}

users/templates/users/pages/password_reset.html
{% extends "layouts/base.html" %}
{% load django_bootstrap5 %}

{% block title %}Сброс пароля{% endblock title %}

{% block content %}
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card shadow">
        <div class="card-body">
          <h2 class="card-title text-center mb-4">Сброс пароля</h2>

          <p class="text-muted text-center mb-4">
            Введите ваш email адрес, и мы вышлем инструкции для сброса пароля.
          </p>

          <form method="POST">
            {% csrf_token %}

            {% bootstrap_form form %}

            <div class="d-grid gap-2">
              <button type="submit" class="btn btn-primary">
                <i class="bi bi-envelope me-2"></i>Отправить инструкции
              </button>
            </div>
          </form>

          <div class="text-center mt-3">
            <a href="{% url 'users:login' %}" class="text-decoration-none">
              <i class="bi bi-arrow-left me-1"></i>Вернуться к входу
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

users/templates/users/pages/password_reset_complete.html
{% extends "layouts/base.html" %}

{% block title %}Пароль изменен{% endblock title %}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card shadow">
                <div class="card-body text-center">
                    <div class="mb-4">
                        <i class="bi bi-check-circle text-success fs-1"></i>
                    </div>
                    <h2 class="card-title mb-4">Пароль изменен!</h2>
                    
                    <p class="text-muted mb-4">
                        Ваш пароль был успешно изменен. Теперь вы можете войти в систему с новым паролем.
                    </p>

                    <div class="d-grid gap-2">
                        <a href="{% url 'users:login' %}" class="btn btn-primary">
                            <i class="bi bi-box-arrow-in-right me-2"></i>Войти в систему
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

users/templates/users/pages/password_reset_form.html
{% extends "layouts/base.html" %}
{% load django_bootstrap5 %}

{% block title %}Ввод нового пароля{% endblock title %}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card shadow">
                <div class="card-body">
                    {% if validlink %}
                        <h2 class="card-title text-center mb-4">Введите новый пароль</h2>

                        <p class="text-muted text-center mb-4">
                            Пожалуйста, введите новый пароль дважды, чтобы мы могли убедиться в правильности написания.
                        </p>

                        <form method="POST">
                            {% csrf_token %}
                            
                            {% bootstrap_form form %}
                            
                            <div class="d-grid gap-2">
                                <button type="submit" class="btn btn-primary">
                                    <i class="bi bi-key me-2"></i>Изменить пароль
                                </button>
                            </div>
                        </form>
                    {% else %}
                        <div class="alert alert-danger text-center">
                            <i class="bi bi-exclamation-triangle me-2"></i>
                            <strong>Ссылка для сброса пароля недействительна.</strong>
                            <p class="mt-2 mb-0">
                                Возможно, она уже была использована. 
                                Пожалуйста, запросите новую ссылку для сброса пароля.
                            </p>
                        </div>
                        
                        <div class="text-center mt-3">
                            <a href="{% url 'users:password_reset' %}" class="btn btn-danger">
                                Запросить новую ссылку
                            </a>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

users/templates/users/pages/password_reset_profile_instructions_sent.html
{% extends "layouts/base.html" %}

{% block title %}Письмо отправлено{% endblock title %}

{% block content %}
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card shadow">
        <div class="card-body text-center">
          <div class="mb-3">
            <i class="bi bi-envelope-check text-success fs-1"></i>
          </div>
          <h2 class="card-title mb-4">Письмо отправлено!</h2>

          <p class="text-muted mb-4">
            Мы отправили инструкции по сбросу пароля на ваш email адрес.
            Вы должны получить письмо в ближайшее время.
          </p>

          <p class="text-muted small">
            Если вы не получили письмо, пожалуйста, проверьте папку "Спам".
          </p>

          <div class="mt-4">
            <a href="{% url 'users:profile' request.user.username %}" class="btn btn-primary">
              <i class="bi bi-arrow-left me-2"></i>Вернуться в профиль
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

users/templates/users/pages/settings.html
{% extends "users/layouts/profile_base.html" %}
{% load static %}

{% block title %}Настройки{% endblock title %}

{% block styles %}
  {{ block.super }}
  <link rel="stylesheet" href="{% static "users/css/pages/settings.css" %}">
{% endblock styles %}

{% block scripts %}
<script>
  window.FIREBASE_API_KEY = "{{ FIREBASE_API_KEY }}";
  window.USER_PHONE_NUMBER = "{{ user.phone_number }}";
  window.MARK_PHONE_NUMBER_AS_VERIFIED_URL = "{% url 'users:mark_phone_number_as_verified' %}";
</script>
<script src="{% static 'users/js/phone-number-verification.js' %}" type="module" defer></script>
{% endblock scripts %}

{% block profile_content %}
<div class="row">
  <div class="col-12">
    <div class="card mb-4">
      <div class="card-header">
        <h2 class="card-title text-center mb-0">
          <i class="bi bi-gear me-2"></i>Настройки аккаунта
        </h2>
      </div>
      <div class="card-body">
        <p class="text-muted text-center">
          Управление настройками вашего аккаунта
        </p>
      </div>
    </div>
  </div>
</div>

<!-- Карточки настроек -->
<div class="row">
  <!-- Смена пароля -->
  <div class="col-md-6 mb-4">
    <div class="card h-100">
      <div class="card-body">
        <div class="d-flex align-items-center mb-3">
          <div class="icon-wrapper bg-primary text-white rounded-circle me-3">
            <i class="bi bi-shield-lock"></i>
          </div>
          <h5 class="card-title mb-0">Смена пароля</h5>
        </div>
        <p class="card-text text-muted mb-3">
          Измените свой текущий пароль на новый (потребуется ввести текущий пароль)
        </p>
        <a href="{% url 'users:password_change' %}" class="btn btn-outline-primary">
          <i class="bi bi-arrow-right me-2"></i>Сменить пароль
        </a>
      </div>
    </div>
  </div>

  <!-- Сброс пароля -->
  <div class="col-md-6 mb-4">
    <div class="card h-100">
      <div class="card-body">
        <div class="d-flex align-items-center mb-3">
          <div class="icon-wrapper bg-warning text-white rounded-circle me-3">
            <i class="bi bi-arrow-clockwise"></i>
          </div>
          <h5 class="card-title mb-0">Сброс пароля</h5>
        </div>
        <p class="card-text text-muted mb-3">
          Сбросьте текущий пароль если забыли его и установите новый (через Email)
        </p>
        <a href="{% url 'users:profile_password_reset' %}" class="btn btn-outline-warning">
          <i class="bi bi-envelope me-2"></i>Сбросить пароль
        </a>
      </div>
    </div>
  </div>

  <!-- Номер телефона -->
  <div class="col-md-6 mb-4 mx-auto">
    <div class="card h-100">
      <div class="card-body">
        <div class="d-flex justify-content-center align-items-center mb-2">
          <div class="icon-wrapper bg-info text-white rounded-circle me-3">
            <i class="bi bi-telephone-fill"></i>
          </div>
          <h5 class="card-title mb-0">Номер телефона</h5>
        </div>

        <div class="phone-content">
          {% if user.phone_number %}
            <div class="d-flex align-items-center justify-content-center mb-3">
              <div class="d-flex flex-column align-items-center">
                <p class="card-text mb-1 fs-4"><strong>{{ user.phone_number }}</strong></p>
                {% if user.phone_number_verified %}
                  <span class="badge bg-success">
                    <i class="bi bi-check-circle me-1"></i>Подтверждён
                  </span>
                {% else %}
                  <span class="badge bg-warning text-dark">
                    <i class="bi bi-exclamation-circle me-1"></i>Не подтверждён
                  </span>
                {% endif %}
              </div>
            </div>


            <div class="btn-group w-100" role="group">
              {% if not user.phone_number_verified %}
                <button class="btn btn-danger flex-fill me-1" data-bs-toggle="modal" data-bs-target="#verifyPhoneNumberModal">
                  <i class="bi bi-shield-check me-2"></i>Подтвердить
                </button>
              {% endif %}
              <button class="btn btn-outline-primary flex-fill" data-bs-toggle="modal" data-bs-target="#setPhoneNumberModal">
                <i class="bi bi-pencil me-2"></i>Изменить
              </button>
            </div>


          {% else %}
            <div class="text-center py-3">
              <i class="bi bi-telephone-x text-muted fs-2"></i>
              <p class="text-muted mt-2 mb-3">Номер телефона не указан</p>

              <button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#setPhoneNumberModal">
                <i class="bi bi-plus-circle me-2"></i>Добавить номер
              </button>
            </div>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Модальные окна -->
{% include "users/includes/set_phone_number_modal.html" %}
{% include "users/includes/verify_phone_number_modal.html" %}
{% endblock profile_content %}